services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: task-manager_app
    restart: always
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    
  nginx:
    image: nginx:1.27-alpine
    container_name: task-manager_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../:/var/www 
      - ./nginx:/etc/nginx/conf.d

  db:
    image: mysql:8.0
    container_name: task-manager_db
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - 3306:3306
    volumes:
      - ./storage/mysql:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql